package ai.learningsystems.gloobermkp.espproxies.plugin.shared.utils;

/**
 * This is a clone of some useful GlooberMkp internal Information System Http Header constants from
 * package ai.learningsystems.gloobermkp.apigateway.domains.share.GatewayHeaderCustomFields
 * 
 * !!! Not be keep in sync !!!
 * 
 * This solution will need some rework.
 * ALl http header custom fields used internally should not be shared externally. 
 * But somes are essentials for coordination.
 * Here we share serviceRef that is used to complete UsageMetrics generated by the plugin.
 * 
 */
public class HttpHeaderSharedConstants
{
    /** Used by API Gateway to pass the serviceRef to espproxies core and plugins */
    final public static String X_GMKP_XSP_SERVICE_REF = "X-GMKP-XSP-SERVICEREF";
    
    /** Message if serviceRef value is not setted in header */
    final public static String SERVICEREF_NOT_SET_IN_HEADER = "SERVICEREF_NOT_SET_IN_HEADER !";
}
